// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRY5QeM8amaEu3lf74whQRudFldGQUGI',
    appId: '1:323974394798:web:1f8ea030c0a0d2ce5b8e3f',
    messagingSenderId: '323974394798',
    projectId: 'graduation-project-d3f62',
    authDomain: 'graduation-project-d3f62.firebaseapp.com',
    storageBucket: 'graduation-project-d3f62.firebasestorage.app',
    measurementId: 'G-YN1QL37FG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDsEGWdO2GZEKudZPcR5zj_lb7leq90E',
    appId: '1:323974394798:android:161982ce89c2508e5b8e3f',
    messagingSenderId: '323974394798',
    projectId: 'graduation-project-d3f62',
    storageBucket: 'graduation-project-d3f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyM-G9DkM2waTIlBiHToiFTvmvHqn4zU',
    appId: '1:323974394798:ios:6d972c9dad2fef265b8e3f',
    messagingSenderId: '323974394798',
    projectId: 'graduation-project-d3f62',
    storageBucket: 'graduation-project-d3f62.firebasestorage.app',
    iosClientId: '323974394798-ehp0rmn0hgtr4q7p7qh34ark6l3dovcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradutionProjectSmartSip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyM-G9DkM2waTIlBiHToiFTvmvHqn4zU',
    appId: '1:323974394798:ios:6d972c9dad2fef265b8e3f',
    messagingSenderId: '323974394798',
    projectId: 'graduation-project-d3f62',
    storageBucket: 'graduation-project-d3f62.firebasestorage.app',
    iosClientId: '323974394798-ehp0rmn0hgtr4q7p7qh34ark6l3dovcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradutionProjectSmartSip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVRY5QeM8amaEu3lf74whQRudFldGQUGI',
    appId: '1:323974394798:web:84090cdacd24c2225b8e3f',
    messagingSenderId: '323974394798',
    projectId: 'graduation-project-d3f62',
    authDomain: 'graduation-project-d3f62.firebaseapp.com',
    storageBucket: 'graduation-project-d3f62.firebasestorage.app',
    measurementId: 'G-YNVVCGSJ62',
  );
}
